version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 4
    groups:
      trpc:
        patterns:
          - "@trpc/*"
      prisma:
        patterns:
          - "@prisma/*"
          - "prisma"
      vee-validate:
        patterns:
          - "@vee-validate/*"
          - "vee-validate"
